"""Initial Migration

Revision ID: 79d8738ef309
Revises: 
Create Date: 2025-04-06 19:41:47.459370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d8738ef309'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('intent', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('entities', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['conversation_id'], ondelete='CASCADE')
        batch_op.drop_column('context_data')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('context_data', sa.Text(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('context_data')
        batch_op.drop_column('language')
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_data', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('entities')
        batch_op.drop_column('intent')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
